import Head from 'next/head'
import Navbar from '../components/Navbar/navbar';
import HeroCard from '../components/HeroCard/heroCard';
import FeatureSection from "../components/FeatureSection/featureSection";
import ProductCarousel from "@/components/ProductCarousel/productCarousel";
import Footer from "@/components/Footer/footer";



export default function Home() {
  return (
    <>
      <Head>
        <title>Duck - Outdoor Retailer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Navbar/>
          <HeroCard/>
          <FeatureSection/>
          <ProductCarousel />
          <Footer />
      </main>
    </>
  )
}
